# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

which_cond <- function(i, j, x, y) {
    .Call(`_pkg_paper_PRS_which_cond`, i, j, x, y)
}

